title: "/p.tt/"
name: John Pettitt
email: j@p.tt
description: John Pettitt's home on the interwebs.
display_footer: "&copy; 2022 John Pettitt. This site does not use cookies or any other tracking technology."
theme: jekyll-theme-midnight
